### ISSUE TITLE
AIM UI Params and Scatter dropdown: Poll server for new menu items

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#1076]
This was implemented with a simple `setInterval` for the Metrics dropdown menu. A similar approach can be used for Params and Scatter, but we probably need to interrupt any existing polling when we switch to a new App, so things get a little more complicated.

See https://github.com/G-Research/fasttrackml-ui-aim/pull/56 for Metrics pulldown polling.

**Comment by dave-gantenbein** [comment]
Let's discuss implementation w/JG before proceeding.

**Comment by jescalada** [comment]
I believe this has been completed here: https://github.com/G-Research/fasttrackml/issues/1127. This is the related PR: https://github.com/G-Research/fasttrackml-ui-aim/pull/68
