### ISSUE TITLE
Allow logging numbers in params

### ISSUE THREAD

**Issue by jescalada** [G-Research/fasttrackml#1218]
Logging numeric params is not possible at the moment as they get converted into strings by the logger, forcing users to log those numbers as metrics instead.

![image](https://github.com/G-Research/fasttrackml/assets/97265671/1b86bc2a-76c2-4450-a08d-18a7661336f3)

**Comment by suprjinx** [comment]
handled in another issue -- use FasttrackML python client to ensure conversion of value to right type.
