### ISSUE TITLE
Redirect from www. to fasttrackml.io

### ISSUE THREAD

**Issue by naskio** [G-Research/fasttrackml#127]
There is currently a DNS error when trying to access [www.fasttrackml.io](http://www.fasttrackml.io/).
The website is only accessible without the "www" at the beginning of the URL. 
We need to set up a redirect from [www.fasttrackml.io](http://www.fasttrackml.io/) to [fasttrackml.io](http://fasttrackml.io/) in order to avoid this error.

**Comment by jgiannuzzi** [comment]
hey @c-rindi, could you please setup a `CNAME` for `www.fasttrackml.io` that points to `g-research.github.io.`?

**Comment by c-rindi** [comment]
Redirect completed. 👍🏽

**Comment by c-rindi** [comment]
Done. 👍🏽

**Comment by c-rindi** [comment]
And www (wildcard) url redirect is also completed. 👍🏽

**Comment by jgiannuzzi** [comment]
@c-rindi could it be that you did it as a redirect with the domain registrar instead of setting up a `CNAME` to `g-research.github.io`? I'm getting certificate errors when I try to go to https://www.fasttrackml.io/

**Comment by c-rindi** [comment]
CNAME Record has been corrected from "@" to "www" and now [www.fasttrackml.io](http://www.fasttrackml.io/) redirects to https://fasttrackml.io/.

**Comment by naskio** [comment]
DNS config should be :ok_hand: now.
We still have one issue: navigating to `https://www.fasttrackml.io/` is causing an SSL certificate issue. We may need to remove and then re-add the custom domain to trigger the process of enabling HTTPS.
Could someone with enough permissions try this please, @suprjinx?

> ...After you update existing DNS settings, you may need to remove and re-add your custom domain to your site's repository to trigger the process of enabling HTTPS. For more information ...
> 

[[Troubleshooting custom domains and GitHub Pages](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors)](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors)

**Comment by jgiannuzzi** [comment]
I've updated the settings and everything is 👌 now — thanks @c-rindi and @naskio!
