### ISSUE TITLE
Support for string functions in Aim query parser

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#13]
e.g. `startswith`, `endswith`, `contains`, ...

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-4) by [Unito](https://www.unito.io)

**Comment by jgiannuzzi** [comment]
if the `in` syntax is too tricky, it's fine to split this into 2 PRs

**Comment by dsuhinin** [comment]
ooook, lets start with `startswith, endswith, contains`

**Comment by dsuhinin** [comment]
@jgiannuzzi can you please give me few examples how the end result should look like? I mean search query with `startswith`, `endswith`, `contains`?
