### ISSUE TITLE
Add new logo in all the UIs

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#135]
We have essentially 2 types of logos: the "full logo" (aka project-logo) and the "icon logo" (aka project-icon). They can be found here: https://github.com/G-Research/fasttrackml/tree/main/website/static/logo.
The new logos should be used in all the following places:

- [x] chooser UI (full + favicon) - dark mode + light mode
  - [x] https://github.com/G-Research/fasttrackml/pull/276
- [x] MLFlow UI (full + favicon)
  - [x] https://github.com/G-Research/fasttrackml-ui-mlflow/pull/9
  - [x] https://github.com/G-Research/fasttrackml/pull/253
- [x] Aim UI (icon + spinner + favicon)
  - [x] https://github.com/G-Research/fasttrackml-ui-aim/pull/20
  - [x] https://github.com/G-Research/fasttrackml-ui-aim/pull/21
  - [x] https://github.com/G-Research/fasttrackml/pull/278

**Comment by suprjinx** [comment]
For MLH fellow
