### ISSUE TITLE
Autocompletion for metrics in Aim UI

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#138]
* When typing `run.` in the various explorers, `metrics` should be available as a suggestion.
* After having typed `run.metrics` in the various explorers, a list of valid metric names should be suggested (e.g. `["loss"]`, `["wps"]`, etc. — they should come from the project's metrics list (`GetProjectParams`)).
* After having type `run.metrics["metric-name"]`, `.last` should be suggested
* when typing `metric.` in the metrics explorer, the following attributes should be suggested: `name` and `last`

**Comment by fabiovincenzi** [comment]
`metric.` support for `name` and `last` is not needed anymore since we removed the support of `metric.` syntax since when we introduced the new metrics selector
