### ISSUE TITLE
Ability to group charts by dynamic expression in the various explorers of the Aim UI

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#139]
**_This issue description is still a work in progress_**

In the Metrics, Params, and Scatters explorers, we currently support grouping by static expressions (for charts, strokes, and colours):
![image](https://github.com/G-Research/fasttrackml/assets/3692455/a363faf0-298f-4644-847c-ec5aa4436501)

The static expressions are attributes of the run, or of the plotted metric:
![image](https://github.com/G-Research/fasttrackml/assets/3692455/a3a4501a-4353-4b13-9de0-a2f453ceb02b)

The feature we would like to add is support for dynamic expressions. These are simple comparisons that evaluate to a boolean and ...

 
e.g. instead of just grouping by `metric.name` or `run.paramX`, you could group by `run.metrics["some-metric"] > 2`

**Comment by jescalada** [comment]
I'd like to take a shot at this issue! Seems pretty challenging, but I think there should be a way to reuse the run filtering logic for grouping too.

**Comment by jescalada** [comment]
This issue is currently on hold as we figure out a way to make the implementation easier or UI refactorings are completed. The progress so far can be found here:

https://github.com/jescalada/fasttrackml-ui-aim/tree/release/v3.17.5-DynamicChartGrouping
