### ISSUE TITLE
Add basic support for OpenID Connect

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#142]
FastTrackML should be able to integrate with a standard OpenID Connect Identity Provider.

When configured for OIDC, all API endpoints (except `/version` and `/health`) will require a valid access token or a valid session cookie.

When browsing to the UI without a valid session cookie, the user should be redirected to the IDP to login. When coming back from the IDP with a valid authentication code and it has been successfully exchanged for access and identity tokens, a session cookie gets created and the user gets redirected to the original requested page.

- [x] #161
  - [x] #162
  - [x] #163
  - [x] #164
- [x] #165
  - [x] #166
  - [x] #167
  - [x] #168
  - [x] #169

**Comment by Sharathmk99** [comment]
This is must needed feature. Any plans to support teams as well??

**Comment by jgiannuzzi** [comment]
Hey @Sharathmk99, thanks a lot for your interest in FastTrackML! Could you please tell us what you mean by "teams"?

**Comment by Sharathmk99** [comment]
I mean group of users(team) It would be nice to have an option to create team/group and assign users to the team. So it will be easy to share experimentation data across multiple users.

**Comment by jgiannuzzi** [comment]
Yes, this is where we want to take FastTrackML after we implement our "namespaces" feature and OpenID Connect support.

**Comment by dave-gantenbein** [comment]
Feature is complete!
