### ISSUE TITLE
Import existing FML database into an instance

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#181]
MVP Requirements (other issues will be created to lift some of these requirements):
* command will be named `import` and take 2 mandatory parameters:
  * `-i`/`--input-database-uri` which takes a database URI (like `server --database-backend-uri`)
  * `-o`/`--output-database-uri` which takes a database URI (like `server --database-backend-uri`)
* input and output databases _must_ be using the latest FML schema (row `version` in table `schema_version`)
  * FML schema will need to become a constant in the code (finally...) — ensure that the constant _has_ to be updated when we create a new migration in the future
  * explain to the user how to migrate the database if the schema is not the latest
* the core logic will be to list objects in the input database and to create objects in the output database
* duplicates are skipped and a warning is logged
* rollback in case of any other error
* warn the user that it is their responsibility to make sure nothing else writes to the database at the same time (both when the command runs and when the command help is displayed)
* Required tables: runs, latest_metrics, experiments, metrics, params, tags, experiment_tags

**Comment by suprjinx** [comment]
In theory, we could just run migration on both input and output to ensure they are at same version -- and then we don't have to write code to compare versions, etc

**Comment by suprjinx** [comment]
added import command ui 
`root ➜ /workspaces/fasttrackml (db-import) $ go run main.go import
FATA[0000] required flag(s) "input-database-uri", "output-database-uri" not set
exit status 1
root ➜ /workspaces/fasttrackml (db-import) $ go run main.go import -h
Copies an input database to an output database

Usage:
  fml import [flags]

Flags:
  -h, --help                         help for import
  -i, --input-database-uri string    Input Database URI (eg., sqlite://fasttrackml.db)
  -o, --output-database-uri string   Output Database URI (eg., postgres://user:psw@postgres:5432)

Global Flags:
  -l, --log-level string   Log level (default "info")
root ➜ /workspaces/fasttrackml (db-import) $`
