### ISSUE TITLE
Import existing MLFlow database into FML database

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#182]
Add the ability to import an existing MLFlow database — _without any migrations or changes to it_ — into an existing or new FML database. This will be a continuation of the work done in #181.
We will need to define a range of supported schema versions and a `--force` flag to allow for future unknown schemas (this may fail if the tables are not how we expect them to be). The way the import will work is by opening the MLFlow database read-only, and then querying the tables we need, with the structure for the basic fields we want to import.

- [x] #294
- [x] #295
- [x] #296

**Comment by dave-gantenbein** [comment]
Please review this for reusability: https://github.com/mlflow/mlflow-export-import
