### ISSUE TITLE
Metric contexts: check that SQLite, DuckDB, and Postgres support querying JSON fields within a column

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#205]
- Need to ensure Gorm supports json querying.
- Context is not flat, need to query nested objects.
- Need to query a variety of types
- Determine if db engines have a max_depth, if so, or if there are perf implications, we may need a story to block that behaviour in the UI

**Comment by suprjinx** [comment]
Findings.

1. Gorm supports JSON for PG, Sqlite, and Mysql -- but not Duckdb.

![Image](https://github.com/G-Research/fasttrackml/assets/1463452/6f2f78ef-952f-499b-9ba2-3e923391acca)

**Comment by jgiannuzzi** [comment]
hey @suprjinx, what about the max depth for querying?

**Comment by suprjinx** [comment]
@jgiannuzzi i am not seeing mention of practical limits for querying nested json in PG or Sqlite docs -- but it seems intuitive we'd encounter this at some point. Perhaps we'd need to create a json document of the expected complexity and verify it with a benchmark test?

**Comment by jgiannuzzi** [comment]
let's have a look at what we can do in Go then in terms of limiting the depth of the JSON query

**Comment by suprjinx** [comment]
I assume we're going to support a context query syntax like Aim's? it seems like we can just "count the dots" and set a limit? This will get translated, most likely, into "->" operator in the sql.

![Image](https://github.com/G-Research/fasttrackml/assets/1463452/365f118b-3287-4341-81ed-530e9eb8433f)
