### ISSUE TITLE
Make artifacts visible in Aim UI

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#228]
Once #6 and #224 are implemented, artifacts will become visible in the MLFlow UI.

This issue is about making them visible in the Aim UI. Aim treats artifacts like metrics and thus expects a few extra properties. Here is how I suggest we map them initially:
| Aim | FML |
| -- | -- |
| name | file name |
| context | `{}` |
| step | `0` |
| epoch | `0` |
| timestamp | file timestamp |

There is also limited support for artifact types. I think we only want to expose images and texts initially. We could detect the file's MIME type to distinguish between images and texts. The search possibilities will be quite limited and tricky unless we implement #225 and use it to store metadata in our database.

**Comment by Sharpz7** [comment]
This would be great to see folks. Thank you :))

**Comment by suprjinx** [comment]
here are the endpoints Aim provides:
https://github.com/aimhubio/aim/blob/main/aim/web/api/tags/views.py
