### ISSUE TITLE
Introduce caching layer for Namespaces

### ISSUE THREAD

**Issue by dsuhinin** [G-Research/fasttrackml#291]
Introduce caching layer for Namespace functionality. We need another level of abstraction which will be on top of current `Namespace` repository. Let's say it will be `NamespaceCachedRepositoryProvider`. Under the hood layer has to work with LRU cache. LRU cache should has different implementation under the hood based on current/active database which is in use and provides just a common interface to use this cache.
**Cache for SQLite Database**:
- Read operation -> firstly tries to read data from the cache. If data exists just return it as is, otherwise  fallback to original `NamespaceRepositoryProvider` to get data from the database, then put data into LRU cache and return it back to the caller.
- Create operation -> create entry right in database and put it to the LRU cache.
- Update, Delete -> just invalidate all entries.

**LRU Cache for Postgres Database**:
In case of Postgres database, could be the case when several instances of `FastTrackML` service use just one database instance. In that case everybody can work with namespaces and apply CRUD operations. It means that we have to notify other instances that something has been changed. We can use `Pub/Sub` mechanism which `Postgres` provides. So:
- Read operation -> firstly tries to read data from the cache. If data exists just return it as is, otherwise  fallback to original `NamespaceRepositoryProvider` to get data from the database, then put data into LRU cache and return it back to the caller.
- Create operation -> create entry right in database and put it to the LRU cache.
- Update, Delete -> just invalidate all entries.
- When something changed on other instances of `FastTrackML` service connected to the same `database` instance, we have to notify `cache` through the `Pub/Sub` to just invalidate all the `namespace` data.

**Comment by jgiannuzzi** [comment]
> the cache invalidation in Postgres with multiple FML instances seems challenging unless the cache itself is a service (Redis eg), but I guess this is a rare event.

no no, Postgres does support pub/sub!
we will have all instances of FML listening to a channel on Postgres, so that in the case of a Update or Delete operation in instance A, we would send a notification to it with the cache name and key. All the other instances will receive this notification and evict the key from the named cache.
