### ISSUE TITLE
Slack channel for communication

### ISSUE THREAD

**Issue by Sharathmk99** [G-Research/fasttrackml#301]
Thank you for this awesome project and focus on performance and scale. I would like to know how backend database is scalable? Do we have any slack or Discord channel for communication ?

thanks.

**Comment by jgiannuzzi** [comment]
Hi @Sharathmk99, thanks for your interest in FastTrackML!

We have a channel on the [MLOps Community](https://mlops.community/) Slack workspace: [`#fasttrackml`](https://mlops-community.slack.com/archives/C05ALNZ1XJN). We're looking forward to your questions!

**Comment by Sharathmk99** [comment]
I tried to fill out the form twice but didn’t receive the slack link to join. Can you help here?

**Comment by c-rindi** [comment]
Hello @Sharathmk99 - we don't own the MLOps Slack group so we're not sure why the form isn't working, but perhaps [this link](https://join.slack.com/t/mlops-community/shared_invite/zt-23zxny538-tiMmR~BzXByKHz1rBxCrqQ) will work better?
Let us know if not and we'll see if we can raise it with them.
Thanks for reaching out!

**Comment by suprjinx** [comment]
I added the slack invite url as a button to the docusaurus site.

![Image](https://github.com/G-Research/fasttrackml/assets/1463452/9b045116-15b6-4087-bf5e-20c77eab7bad)

**Comment by Sharathmk99** [comment]
Thank you so much.

**Comment by suprjinx** [comment]
The development plans for this ticket have moved to #450
