### ISSUE TITLE
Improve description of FastTrackML in the README

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#353]
New users looking at our README wouldn't know what makes FastTrackML unique and why they should bother trying it over MLFlow or other experiment trackers. We should better describe what it does and what it does better than the rest.

Our website has a highlights section that explains this in a few impactful words. We should expand on that in the README.

**Comment by ashutoshbr** [comment]
Hi there,

Having more content, such as documentation, screenshots, or gifs, could really enhance the README. But I could not find much content at https://fasttrackml.io/
I am not sure if this is how it should be done; any suggestions are highly appreciated
Thanks!
![ss](https://github.com/G-Research/fasttrackml/assets/66586932/f24aed8d-ce30-439f-97fa-c20ae96e25a0)
