### ISSUE TITLE
Refactor data access in AIM api

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#36]
Some of the refactorings for the MLFlow side can be reused directly in the Aim API (eg, services and dao/models, dao/repositories). Otherwise, introduce Aim-api specific layers that mirror the work done on MLFlow api (eg, controllers, converters, etc).

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-1) by [Unito](https://www.unito.io)

**Comment by jgiannuzzi** [comment]
Superseded by #333
