### ISSUE TITLE
Prepare the base for integration tests

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/fasttrackml#37]
Prepare the base for integration tests for `mlflow` part. Integrate it into the `github` actions pipeline. Create few real tests as an example so we can use the same approach for `aim` api.

┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-19) by [Unito](https://www.unito.io)

**Comment by Cijin** [comment]
Since this issue is marked as done in the FastTrackML project, should this issue be closed?
