### ISSUE TITLE
AIM UI there is no option to update Run description

### ISSUE THREAD

**Issue by dsuhinin** [G-Research/fasttrackml#373]

**Comment by vinayan3** [comment]
@fabiovincenzi I also looked at this issue. I took a slightly different approach on the UI side. The PR you put up in :https://github.com/G-Research/fasttrackml-ui-aim/pull/97/files  has the UI read `ID` but instead in lower case `id`. 

Also, for grabbing the tag I chose to make the server find it.

 Would you be open to taking in a patch for the server using the designated fields and rolling back changes to the UI? In the future, it will reduce potential merge conflicts from the upstream AIM UI.
