### ISSUE TITLE
AIM UI there is no logic to support Tag functionality

### ISSUE THREAD

**Issue by dsuhinin** [G-Research/fasttrackml#374]
In AIM UI we have a tag management section, but API fully missing to support that.

![Image](https://github.com/G-Research/fasttrackml/assets/7852635/fbc46b7f-f0b4-4f6f-aa93-42eb61421f4d)

**Comment by suprjinx** [comment]
here are the tag endpoints: 
https://github.com/aimhubio/aim/blob/main/aim/web/api/tags/views.py
