### ISSUE TITLE
Revamp "Contact Us" with Automated Slack Invite Link

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#450]
Ticket derived extended from #301. 

We would like to remove the` Contact Us` form and header link, and instead just have Email Us (mailto: link), Github, and Slack links in the header.

The Slack link will be an `MLOps.community` invite link for the `#fasttrackml` channel. This link needs to be autogenerated once per week.

**Comment by suprjinx** [comment]
we can change the invite link to "Never expires" so the autogeneration part is not needed. 

![Image](https://github.com/G-Research/fasttrackml/assets/1463452/352ed04a-ca0b-4959-b615-54ffc0075fd0)

**Comment by c-rindi** [comment]
@naskio any feedback, since you set this up originally?

**Comment by suprjinx** [comment]
so header like this?

![Image](https://github.com/G-Research/fasttrackml/assets/1463452/9c64a0c9-7a41-4f2e-a129-9c5d2b5c0ee3)
