### ISSUE TITLE
Use `code` in list of namespaces on chooser

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#477]
on the chooser, the namespaces are listed with the `description` field only. Since this is not a required field, they are sometimes just blanks. 

Use the `code`  column in the listing.

**Comment by jgiannuzzi** [comment]
I don't think we should do that. Instead we should rename `description` as `label` and make it required and limited in size (25 chars?). The `code` could default to the lowercased spaces-replaced-by-dashes representation of `label` in the form (via a bit of client-side JS)

**Comment by dave-gantenbein** [comment]
Fixed by #622
