### ISSUE TITLE
AIM ignore NaN metric values for Y axis limits?

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#489]
User Stephen Chestnut reports: "if a metric has some runs with nan and some runs with numeric values then the plot in metrics explorer just looks empty, and with no y-axis ticks, until I specify the y-range using the "Axis-properties" button.  Is possible to make AIM ignore nans when it auto-selects the axes limits?"

**Comment by stephche222** [comment]
The same issue happens with inf and -inf, can it ignore those too, please?
