### ISSUE TITLE
Improve database migrations with better dev tooling

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#520]
Our database migrations are currently way too manual and have become quite unwieldy. We should investigate migration tools in the Go ecosystem that are compatible with Gorm, like [Atlas](https://atlasgo.io) and its [Gorm provider](https://github.com/ariga/atlas-provider-gorm).

**Comment by dave-gantenbein** [comment]
Investigate:

[Atlas](https://atlasgo.io)
[Goose](https://github.com/pressly/goose)
[Go Migrate](https://github.com/golang-migrate/migrate)

Minimum requirements:
- Ability to run arbitrary business logic during migrations
- Extensive backend support (existing dbs plus duckdb)
- Versioned migrations
- Sensible automation for most use cases
- Up/Down (ie rollbacks)

Demonstrate for each tool:
 - Add/remove column, with computed value
 - Change primary key to composite
 - Add table with foreign key

**Comment by suprjinx** [comment]
after discussion with the team, it seems every tool will involve some tradeoffs like we currently experience -- so for the moment, we will stick with devil we know, but add "generator" make target to setup a new migration easily. This will:

1) make a new module and versionID for the migration, and create the files.
2) update `database/migrate.go` to reference this new migration as the latest.
3) encourage creating "up" and "down" steps going forward.
4) add developer docs describing usage and next steps.
