### ISSUE TITLE
Fix parameter logging of duplicates

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#523]
Issue #43 was not completely implemented. For compatibility with MLFlow tracking server, we need:
1) 400 error when batch contains same key/different value parameter (currently returns 500)
2) 200 for same key/same value needs to work across batches, not just within batches.

**Comment by jgiannuzzi** [comment]
I think that this could be efficient:
- Use ON CONFLICT DO NOTHING
- Check the amount of inserted rows
- If it matches the amount of rows we tried to insert, we’re done
- If not, we can check whether any of our rows has a different value and return an error if that’s the case (it doesn’t matter as much how this is done as it’s not on the hot path anymore)
