### ISSUE TITLE
Support logging of system metrics

### ISSUE THREAD

**Issue by diggerk** [G-Research/fasttrackml#536]
Aim has a support for logging system metrics such as CPU/GPU/network/memory utilization. MLflow has just added a support for it in 2.8.0. It'd be nice to have FML support it, too. Maybe it'd already work out of the box with the new MLflow client, but most likely the special functionality for system metrics that exists in Aim UI (showing/hiding system metrics in one go) would still need some work.

From MLflow 2.8.0 release notes:
> [Tracking] Add support for logging system metrics to the MLflow fluent API (https://github.com/mlflow/mlflow/pull/9557, https://github.com/mlflow/mlflow/pull/9712, https://github.com/mlflow/mlflow/pull/9714, @chenmoneygithub)

**Comment by jgiannuzzi** [comment]
Thank you so much for reporting this @diggerk!

We have just merged https://github.com/G-Research/fasttrackml-ui-aim/pull/33 and #780 which add support for this feature. Once you enable system metrics logging via `mlflow.enable_system_metrics_logging()`, they will become available in both UIs, with the special treatment that you would expect from the Aim UI (hide/show, etc.).

This is currently only available on `main` (which is also tagged as `edge` for the container image), which we do _not_ recommend for production use. Let us know if you would like us to backport this feature to our 0.4.x series!

**Comment by diggerk** [comment]
Thanks a lot for implementing this!
