### ISSUE TITLE
Integration tests for MLFlow metrics API

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#56]
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-38) by [Unito](https://www.unito.io)

**Comment by suprjinx** [comment]
we do seem to have some tests for the metrics endpoints -- handled in another ticket?

**Comment by dave-gantenbein** [comment]
Ancient ticket, not needed anymore
