### ISSUE TITLE
Metric contexts: adapt the database schema

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#580]
At the very least, a new column with JSON type needs to be added to the `metrics` and `latest_metrics` tables. Ideally we would normalize the metrics IDs by having a new `metrics` table that maps a `key` and `context` to an `id`, and then reference those IDs in `metric_values` and `latest_metric_values` (new table names) instead of the `key`.

**Comment by suprjinx** [comment]
I'm not sure I understand the normalized approach here. Is this because every metric for a run will have identical context, so we want to reduce storage?

**Comment by jgiannuzzi** [comment]
Not just storage but also lookup times. Imagine you have 1000 runs that log 100 metrics of 10000 steps each. The metric contexts will be duplicated 10,000,000 times and any lookup will need to examine all of these. We inherited our schema from the MLFlow one, and it really doesn't scale further without more normalisation.
I would like us to not build more tech debt with this new feature. The rest of the normalisation (params and tags) can happen later.
