### ISSUE TITLE
Add logarithmic scale in the params explorer of the Aim UI

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#67]
The metrics explorer of the Aim UI allows to change the scale of the X and Y axis from linear to logatrithmic, like in the screenshot below:

![Image](https://github.com/G-Research/fasttrackml/assets/3692455/32072e15-f152-415e-9883-4f980302db73)

We need to have the same feature in the params explorer, not per axis, but per choosen param/metric. In the screenshot below, there should be an additional button to the right of the graph pane, that would then open a popup allowing to choose between linear and logarithmic for `metric1` and for `param1`:

![Image](https://github.com/G-Research/fasttrackml/assets/3692455/149fff89-e198-4533-ab4e-cc4d07516725)

This should not require changes to the backend, but only to the frontend bits so that it configures the graph library in the requested way.

**Comment by jescalada** [comment]
Hi, I just started work on this issue and made a quick mockup of what the feature might look like:

![67_quick_mockup](https://github.com/G-Research/fasttrackml/assets/97265671/81c05869-c105-44c4-965b-ae4dc5d87fdb)

If I understand correctly, we want to treat each metric as an "independent" axis which can be log or linear.

I was wondering what we should do if there are many (6+) metrics being tracked simultaneously. Should we add a scrollbar to the popover to prevent it from overflowing on smaller screen sizes?

My plan is to create a `MetricsScalePopover` by adapting the existing `AxesScalePopover` and related classes. The main difference is that for the equivalent `ScaleState` interface we'll have a `ScaleEnum[]` to track each metric's state, and that we need to update the popover whenever the tracked metrics change.

Let me know if there are any issues or things I should keep in mind!

**Comment by jescalada** [comment]
I just realized I mixed up Params with Metrics. "Params scale" is what I meant to say!
