### ISSUE TITLE
MLFlow python client: add context to `GetMetricHistory` (?) and `GetMetricHistories`

### ISSUE THREAD

**Issue by suprjinx** [G-Research/fasttrackml#671]
`GetMetricHistories` accepts a json body from a post, so adding context is pretty easy -- `GetMetricHistory` is GET with url params only, and map params are not supported.

Outstanding question: how is context represented here? stringified json? or json sub object at key 'context'

**Comment by suprjinx** [comment]
![Image](https://github.com/G-Research/fasttrackml/assets/1463452/7f50e8ad-87d4-4852-8030-b3210719c61d)

verified in `batch.py` with the code above -- but I think this should be added to the FasttrackML client

**Comment by jgiannuzzi** [comment]
duplicate of #363
