### ISSUE TITLE
Add fml binary to releases

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#77]
┆Issue is synchronized with this [Jira Task](https://gr-oss.atlassian.net/browse/FML-59) by [Unito](https://www.unito.io)

**Comment by dave-gantenbein** [comment]
Goal: all binaries are pushed to GH release

**Comment by suprjinx** [comment]
I think this story will be much easier when we have a pure-go build -- the Node build phase isn't goreleaser-friendly!
