### ISSUE TITLE
pip package installation doesn't install client, only server

### ISSUE THREAD

**Issue by lkoelman** [G-Research/fasttrackml#905]
installing `fasttrackml` through pip installs the `fml` script to start the server just fine.

However, trying to `import fasttrackml` raises a `ModuleNotFoundError`. This makes it impossible to use the FastTrackML client.

**Comment by lkoelman** [comment]
If anyone stumbles upon this: building from source and installing the resulting wheel seems to work.

Instructions:

```sh
# in a python >= 3.11 environment:
pip install pipenv

git clone https://github.com/G-Research/fasttrackml.git
cd fasttrackml
make python-env
make python-dist

# install in your target environment
source /path/to/my-venv/bin/activate
pip install ./wheelhouse/FastTrackML*.whl
```

**Comment by jgiannuzzi** [comment]
Thanks for your interest in FastTrackML @lkoelman!

The client is not necessary when using the stable release (0.4.0 at the time of writing).
Our 0.5.x branch introduced support for metric contexts, so if you install 0.5.0b2 you will have both the client and the server.

Let us how it goes!

**Comment by jgiannuzzi** [comment]
Wheels have been on PyPI all along 😄
```bash
pip install fasttrackml==0.5.0b2
```
