### ISSUE TITLE
Allow using metric contexts with a "safe" client

### ISSUE THREAD

**Issue by jgiannuzzi** [G-Research/fasttrackml#923]
MLFlow provides `mlflow.utils.autologging_utils.client.MlflowAutologgingQueueingClient` as a client implementation that can queue all the logging calls and won't raise exceptions.

We should have a way to log metric contexts with a similar client (maybe via mix-ins?).

**Comment by suprjinx** [comment]
we did add "Synchronous" param to `log_metric` s
