### ISSUE TITLE
SPIKE: look for golang user management middleware that solves basic user login and management tasks

### ISSUE THREAD

**Issue by dave-gantenbein** [G-Research/fasttrackml#977]

**Comment by suprjinx** [comment]
There are a number of modules that we could use: https://github.com/avelino/awesome-go?tab=readme-ov-file#authentication-and-oauth

**Comment by suprjinx** [comment]
Solution discussed in meeting: https://github.com/orgs/G-Research/projects/19/views/2?filterQuery=&pane=issue&itemId=56047102

**Comment by dave-gantenbein** [comment]
Not moving forward with this approach.
